name: OpenPDF Maven Build

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows-latest
          java: 21
          arch: x64
          runner: windows-latest
        - os: windows-latest
          java: 25
          arch: x64
          runner: windows-latest
    name: Build with Java ${{ matrix.java }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5

    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}

    - name: Check Maven version and directory contents
      shell: bash
      run: |
        ./mvnw -v
        echo "** ls **"
        pwd && ls -l

    - name: Build with Maven
      run: ./mvnw -B install --file pom.xml
